### ISSUE TITLE
Tweak SG param printing in fitNi

### ISSUE THREAD

**Issue by sbanerjee23** [diffpy/cmi_exchange#13]
Hey @pavoljuhas 

Was thinking it might be more useful to print the space group params that are being refined, instead of all available space group params. Or both. 

So we could do this in the SG iteration like this:

```python
for par in spaceGroupParams.latpars:
        recipe.addVar(par, fixed=False, tag='lat')
        print par.name
```

I'm usually printing the structure, the available SG params, and the refined SG params. An output like this has been useful for me. Note that here since I'm not cycling through `xyzpars`, the available SG par `z_4` isn't refined:

```
Anatase_test1
lattice=Lattice(a=3.7842, b=3.7842, c=9.5146, alpha=90, beta=90, gamma=90)
Ti   0.000000 0.500000 0.250000 1.0000
Ti   0.000000 0.000000 0.000000 1.0000
Ti   0.500000 0.000000 0.750000 1.0000
Ti   0.500000 0.500000 0.500000 1.0000
O    0.000000 0.500000 0.458100 1.0000
O    0.000000 0.000000 0.791900 1.0000
O    0.000000 0.500000 0.041900 1.0000
O    0.000000 0.000000 0.208100 1.0000
O    0.500000 0.000000 0.958100 1.0000
O    0.500000 0.500000 0.291900 1.0000
O    0.500000 0.000000 0.541900 1.0000
O    0.500000 0.500000 0.708100 1.0000
('Available SG parameters are:', 'a, c, z_4, U11_0, U33_0, U11_4, U22_4, U33_4')

Refining the following SG paramters
----------------------------------------------------------------------------------------------------
a
c
U11_0
U33_0
U11_4
U22_4
U33_4
----------------------------------------------------------------------------------------------------
Running fit...

Some quantities invalid due to missing profile uncertainty
Overall (Chi2 and Reduced Chi2 invalid)
-------------------------------------------------------------------------------
Residual       84.92886484
Contributions  84.92886484
Restraints     0.00000000
Chi2           84.92886484
Reduced Chi2   0.01754366
Rw             0.10229710

Variables (Uncertainties invalid)
-------------------------------------------------------------------------------
U11_0   6.20989898e-03 +/- 4.98275340e+03
U11_4   1.58901333e-02 +/- 1.30451041e+04
U22_4   1.58901333e-02 +/- 1.25854378e+04
U33_0   6.20989898e-03 +/- 2.93448028e-04
U33_4   1.58901333e-02 +/- 7.93611279e-04
a       3.78441511e+00 +/- 7.30256148e-04
c       9.50289422e+00 +/- 2.85479113e-03
delta1  1.08937988e+00 +/- 8.24891639e-02
psize   6.95505447e+01 +/- 2.89603473e+00
s1      8.89206894e-01 +/- 1.99759272e-02
```

**Comment by pavoljuhas** [comment]
I agree it would be good to display both the available and refined space group parameters.  It does not make difference for nickel, but it would be useful for adapting nickel script to other structures.

As for the anatase, a simpler solution is to set the anisotropy flag of the sites you want to have anisotropic, e.g.,
```python
ana = loadStructure('tio2-anatase.cif', 'cif')
ana[ana.element == "O"].anisotropy = True
```
When CIF provides only `_atom_site_B_iso_or_equiv` the loaded structure assumes that all sites have isotropic displacements and sets `anisotropy == False`.  The flag permits only isotropic Uij matrices and is not changed by the `constrainAsSpaceGroup` function; this is arguably a bug.  For now the workaround is to explicitly set `anisotropy` for the sites that should be treated as such; this should do it without exporting-CIF through PDFgui.

**Comment by sbanerjee23** [comment]
Thanks Pavol, the anisotropy flag worked great. I was able to use it both after defining a generator, or after importing the structure (simpler). 

```python
stru1 = Structure(filename=os.path.join(strudir, cif_path))

generator_anatase = PDFGenerator("G1")
generator_anatase.setStructure(stru1, periodic=True)
generator_anatase.stru[generator_anatase.stru.element == "O"].anisotropy = True
 
# Or

stru1[stru1.element=="O"].anisotropy = True
generator_anatase = PDFGenerator("G1")
generator_anatase.setStructure(stru1, periodic=True)
```
The SG param printing is basically just personal preference type thing, because I realized the FitResults already show which of the available SG params are refined, so I think it's clear as is in both the Ni example and future example scripts. I'll submit a PR for some of these soon, and am also making some notebooks for myself, so maybe we can talk about whether those are helpful or not.

**Comment by pavoljuhas** [comment]
> `stru1 = Structure(filename=os.path.join(strudir, cif_path))`

A small point - here it is actually better to use `loadStructure()` function.
The `Structure(filename=...)` can create only an instance of Structure class,
but function can return different types based on a type of the file.
(In a future we should add `Molecule` class for non-periodic clusters.)

**Comment by sbanerjee23** [comment]
Interesting. I've used `Structure` in the past to make recipes with both periodic and discrete structure inputs. For example: 

```python
stru1 = Structure(filename="Ag_4071NN_5sh.xyz")
stru2 = Structure(filename="Ag_8_8_8_marks.xyz")
stru3 = Structure(filename="AgAuComb.cif")
stru4 = Structure(filename="LaB6_NISTSRM_660a.cif")

########################################################

def makeRecipe(stru1, stru2, stru3, stru4, datname):
    profile = Profile()
    parser = PDFParser()
    parser.parseFile(datname)
    profile.loadParsedData(parser)
    profile.setCalculationRange(xmin=1.5, xmax = 20.0, dx = 0.01)
   
    generator_molecule1 = DebyePDFGenerator("G1")
    generator_molecule1.setStructure(stru1, periodic=False)
    generator_molecule2 = DebyePDFGenerator("G2")
    generator_molecule2.setStructure(stru2, periodic=False)

    generator_crystal1 = PDFGenerator("G3")
    generator_crystal1.setStructure(stru3, periodic=True)
    generator_crystal2 = PDFGenerator("G4")
    generator_crystal2.setStructure(stru4, periodic=True)
```
Is it necessary to use the `loadStructure()` function if we specify generators as above? In fact this is the reason why I use `Structure` with `PDFGenerator` and `DebyePDFGenerator`, specifically to allow this flexibility.

**Comment by pavoljuhas** [comment]
> Is it necessary to use the loadStructure() function if we specify generators as above?

Currently both forms do the same thing.  In the future the Structure(filename=...) form is likely to break whereas loadStructure will keep working.  It is therefore better to use loadStructure in any new code.

**Comment by sbanerjee23** [comment]
Thanks Pavol, will make the change.

**Comment by PPguyz** [comment]
Hi everybody;
 I just want to do the job in 2 steps;
 step 1. I wanna give an adp value which is fixed[fixed=True],
 step 2. let it refine(not fixed[fixed=False]).

 Also, I can not see what is inside array "spaceGroupParams", when I print it:

In[1]: print(spaceGroupParams)

Out[1]: <diffpy.srfit.structure.sgconstraints.SpaceGroupParameters object at 0x7fa0c24c9b10>

I would be most appreciated for your generous guidance.
